version: "3"
services:
  basement-closet:
    image: basement-closet
    build: 
      context: .
    environment:
      DBHOST: database
      DBPORT: 3306
      DBUSER: root
      DBPWD: mamamaria
      DBNAME: basement-closet
  database:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: mamamaria
      MYSQL_DATABASE: basement-closet