version: "3"
services:
  basement-closet:
    image: basement-closet
    build: 
      context: .
    environment:
      DBHOST: database
      DBPORT: 3306
      DBUSER: root
      DBPWD: mamamaria
      DBNAME: basement-closet
      WAIT_BEFORE_HOSTS: 3
      WAIT_HOSTS: database:3306
      WAIT_HOSTS_TIMEOUT: 30
      WAIT_SLEEP_INTERVAL: 1
      WAIT_HOST_CONNECT_TIMEOUT: 10
    ports:
      - 8080:8080
    command: --port 8080 --host 0.0.0.0

  database:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: mamamaria
      MARIADB_DATABASE: basement-closet
    ports:
      - 3306:3306
